export const data = [
	{
		id: 1,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeM4ZnJoCeLc4AdxHFKpfKTy_ApKKvsgu9zw&usqp=CAU",
		title: "NFT 1",
		desc: "The Great Western Railway War Memorial is a First World War memorial by Charles Sargeant Jagger and Thomas S. Tait. It stands on platform 1 at London Paddington station, commemorating the 2,500 Great Western Railway (GWR) employees killed in the conflict. A third of the GWR's workforce of almost 80,000 left to fight in the war, the company guaranteeing their jobs. The memorial consists of a bronze statue of a soldier in heavy winter clothing, reading a letter from home. The statue stands on a polished granite plinth, within a white stone surround. The names of the dead are on a roll buried in the plinth. GWR chairman Viscount Churchill unveiled the memorial on 11 November 1922 in front of over 6,000 people, including the Archbishop of Canterbury, GWR officials, and relatives of the dead. When public gatherings were restricted during the COVID-19 pandemic, local communities on the GWR network laid",
		bg: "f5fafd",
		price: "$100",
	},
	{
		id: 2,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxX6lnYB7qYk3PJ4PvxoufZaSe8WQfSK6imWvgBNgJ-Xm6xBr6K34HtuR_9Gr11mfuvS8&usqp=CAU",
		title: "NFT 2",
		desc: "The Great Western Railway War Memorial is a First World War memorial by Charles Sargeant Jagger and Thomas S. Tait. It stands on platform 1 at London Paddington station, commemorating the 2,500 Great Western Railway (GWR) employees killed in the conflict. A third of the GWR's workforce of almost 80,000 left to fight in the war, the company guaranteeing their jobs. The memorial consists of a bronze statue of a soldier in heavy winter clothing, reading a letter from home. The statue stands on a polished granite plinth, within a white stone surround. The names of the dead are on a roll buried in the plinth. GWR chairman Viscount Churchill unveiled the memorial on 11 November 1922 in front of over 6,000 people, including the Archbishop of Canterbury, GWR officials, and relatives of the dead. When public gatherings were restricted during the COVID-19 pandemic, local communities on the GWR network laid",
		bg: "f5fafd",
		price: "$100",
	},
	{
		id: 3,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaclhA9X4DfVWLQlplVTuw73YrDExSLe5I02XEdmlKqVhADU7yo-CwqeuMeRlWJGluYKM&usqp=CAU",
		title: "NFT 3",
		desc: "The Great Western Railway War Memorial is a First World War memorial by Charles Sargeant Jagger and Thomas S. Tait. It stands on platform 1 at London Paddington station, commemorating the 2,500 Great Western Railway (GWR) employees killed in the conflict. A third of the GWR's workforce of almost 80,000 left to fight in the war, the company guaranteeing their jobs. The memorial consists of a bronze statue of a soldier in heavy winter clothing, reading a letter from home. The statue stands on a polished granite plinth, within a white stone surround. The names of the dead are on a roll buried in the plinth. GWR chairman Viscount Churchill unveiled the memorial on 11 November 1922 in front of over 6,000 people, including the Archbishop of Canterbury, GWR officials, and relatives of the dead. When public gatherings were restricted during the COVID-19 pandemic, local communities on the GWR network laid",
		bg: "f5fafd",
		price: "$100",
	},
	{
		id: 4,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTElIxPmIy7V3LOpAjUNB2oHuaI5DxzLDEl5eaC_npTnoQ7Gxp3vyBAT5fWG1ySHAFLEps&usqp=CAU",
		title: "NFT 4",
		desc: "The Great Western Railway War Memorial is a First World War memorial by Charles Sargeant Jagger and Thomas S. Tait. It stands on platform 1 at London Paddington station, commemorating the 2,500 Great Western Railway (GWR) employees killed in the conflict. A third of the GWR's workforce of almost 80,000 left to fight in the war, the company guaranteeing their jobs. The memorial consists of a bronze statue of a soldier in heavy winter clothing, reading a letter from home. The statue stands on a polished granite plinth, within a white stone surround. The names of the dead are on a roll buried in the plinth. GWR chairman Viscount Churchill unveiled the memorial on 11 November 1922 in front of over 6,000 people, including the Archbishop of Canterbury, GWR officials, and relatives of the dead. When public gatherings were restricted during the COVID-19 pandemic, local communities on the GWR network laid",
		bg: "f5fafd",
		price: "$100",
	},
	{
		id: 5,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi4GNGlSDL6XH5qEHBB8cJJKOIwnEOQF-o2fLRzT7KRR5xq8qSUE0iGdB4MmZ2muFfD-4&usqp=CAU",
		title: "NFT 5",
		desc: "The Great Western Railway War Memorial is a First World War memorial by Charles Sargeant Jagger and Thomas S. Tait. It stands on platform 1 at London Paddington station, commemorating the 2,500 Great Western Railway (GWR) employees killed in the conflict. A third of the GWR's workforce of almost 80,000 left to fight in the war, the company guaranteeing their jobs. The memorial consists of a bronze statue of a soldier in heavy winter clothing, reading a letter from home. The statue stands on a polished granite plinth, within a white stone surround. The names of the dead are on a roll buried in the plinth. GWR chairman Viscount Churchill unveiled the memorial on 11 November 1922 in front of over 6,000 people, including the Archbishop of Canterbury, GWR officials, and relatives of the dead. When public gatherings were restricted during the COVID-19 pandemic, local communities on the GWR network laid",
		bg: "f5fafd",
		price: "$100",
	},
	{
		id: 6,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_XJTe901mMSYLxw-ijrDnCdf87V8Pad0UZj6Q2DFtSedTqC0GDT6O-k_IJEEvkHWZXn0&usqp=CAU",
		title: "NFT 6",
		desc: "The Great Western Railway War Memorial is a First World War memorial by Charles Sargeant Jagger and Thomas S. Tait. It stands on platform 1 at London Paddington station, commemorating the 2,500 Great Western Railway (GWR) employees killed in the conflict. A third of the GWR's workforce of almost 80,000 left to fight in the war, the company guaranteeing their jobs. The memorial consists of a bronze statue of a soldier in heavy winter clothing, reading a letter from home. The statue stands on a polished granite plinth, within a white stone surround. The names of the dead are on a roll buried in the plinth. GWR chairman Viscount Churchill unveiled the memorial on 11 November 1922 in front of over 6,000 people, including the Archbishop of Canterbury, GWR officials, and relatives of the dead. When public gatherings were restricted during the COVID-19 pandemic, local communities on the GWR network laid",
		bg: "f5fafd",
		price: "$100",
	},
	{
		id: 7,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ1tE6BZdfkYKqiG5QevZBuS8eNYGslc_o_alUa2dsq6fqZYFmGpGrrzcITmRHcnUFPEk&usqp=CAU",
		title: "NFT 7",
		desc: "The Great Western Railway War Memorial is a First World War memorial by Charles Sargeant Jagger and Thomas S. Tait. It stands on platform 1 at London Paddington station, commemorating the 2,500 Great Western Railway (GWR) employees killed in the conflict. A third of the GWR's workforce of almost 80,000 left to fight in the war, the company guaranteeing their jobs. The memorial consists of a bronze statue of a soldier in heavy winter clothing, reading a letter from home. The statue stands on a polished granite plinth, within a white stone surround. The names of the dead are on a roll buried in the plinth. GWR chairman Viscount Churchill unveiled the memorial on 11 November 1922 in front of over 6,000 people, including the Archbishop of Canterbury, GWR officials, and relatives of the dead. When public gatherings were restricted during the COVID-19 pandemic, local communities on the GWR network laid",
		bg: "f5fafd",
		price: "$100",
	},
	{
		id: 8,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMNVW1TOu8D65ZPh1dHQBM5EyYW4J8ecjp22tjbJT1LXf54a9JGJGTE0Q6-bJ75ypfnJc&usqp=CAU",
		title: "NFT 8",
		desc: "punk 1800",
		bg: "f5fafd",
		price: "$100",
	},
	{
		id: 9,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyIpwncBqpf8lKIVCb9K3_M8jj3zlxbPo6nGAUVX46UJvf_raPIiavU5xoJwKbZ7ni_jI&usqp=CAU",
		title: "NFT 9",
		desc: "punk 1900",
		bg: "f5fafd",
		price: "$100",
	},
	{
		id: 10,
		img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmhAVHmHPXLxmoOBrDmahWZKodopUvNAD516xnFxi0w5iAGBWlCL0de2LjPAZfenHB1xM&usqp=CAU",
		title: "NFT 10",
		desc: "punk 2000",
		bg: "f5fafd",
		price: "$100",
	},
];
